modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/cech12/ExtendedMushrooms/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="extendedmushrooms"
    version="${file.jarVersion}"
    displayName="Extended Mushrooms"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/extended-mushrooms"
    authors="Cech12"
    description='''
    This mod changes some mushroom behaviour and adds mushroom related blocks, items and recipes.
    '''
[[dependencies.extendedmushrooms]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.extendedmushrooms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"